#user post
###
POST http://127.0.0.1:8080/users
Content-Type: application/json

{
  "id": 1,
  "firstName": "Mohammad Reza",
  "lastName": "Tashakori Beheshti",
  "birthdate": "2000-04-07"
}

###
POST http://127.0.0.1:8080/users
Content-Type: application/json

{
  "id": 2,
  "firstName": "Adel",
  "lastName": "Jalal Ahmadi",
  "birthdate": "2000-04-01"
}